### ISSUE TITLE
question - which file is the main dataset?

### ISSUE THREAD

**Issue by jhpoelen** [BDMYRepository/Echino-Interactions#2]
Hi @RosaSotelo1 thanks for updating the data. 

I was reviewing the data and I noticed two data file:

Interactions.csv (with capital I)

and

interactions.tsv (all lower case)

I noticed they are slightly different (different columns). Which one is the "master" copy? Or which one would you like to use?

A related note: 

GloBI is picky about capitalization and only detects all lower case ```interactions.csv``` or ```interactions.tsv```. So, if you use a filename ```Interactions.csv```, or ```Interactions.tsv```, GloBI will not use it ; ( .

**Comment by RosaSotelo1** [comment]
Thranks for reviewed,

I changed the I for i. Both archives contain exactly same information, but if it's necesary appoint one as "master", it's interactions.cvs

**Comment by jhpoelen** [comment]
Thanks for your quick reply - and for fixing the capitalization! Also, I'd suggest to remove the ```interactions.tsv``` and only keep the ```interactions.csv``` to avoid extra work in keeping the files in-sync.

**Comment by jhpoelen** [comment]
Thanks for updating your dataset!
